### ISSUE TITLE
希望可以给封装的.jar服务端加更多功能

### ISSUE THREAD

**Issue by Walkersifolia** [7aGiven/PhigrosLibrary#2]
比如获取的信息，全曲的成绩数据，或者修改数据的功能（咕咕

**Comment by Dragon-ts** [comment]
btw源码里有.java呀，改改就能放在jar包里啊_(:з」∠)_

**Comment by Walkersifolia** [comment]
> btw源码里有.java呀，改改就能放在jar包里啊_(:з」∠)_

https://i0.hdslb.com/bfs/new_dyn/1f24741ae024c83ac18975674d0378743493095668713929.gif@135h_!web-comment-note.avif
0.0我看看去

**Comment by Dragon-ts** [comment]
> > btw源码里有.java呀，改改就能放在jar包里啊_(:з」∠)_
> 
> https://i0.hdslb.com/bfs/new_dyn/1f24741ae024c83ac18975674d0378743493095668713929.gif@135h_!web-comment-note.avif
> 0.0我看看去

猫对立，すき

**Comment by 7aGiven** [comment]
已实现

**Comment by Walkersifolia** [comment]
您（
