### ISSUE TITLE
gameKey 似乎更新到了 version 2

### ISSUE THREAD

**Issue by Lama3L9R** [7aGiven/PhigrosLibrary#4]
看了许久 java 库代码，gameKey 文件第一个字节应该是文件版本号，我这里新鲜下载的文件的第一个字节变成了 2，大抵是库需要更新了

**Comment by 7aGiven** [comment]
> 看了许久 java 库代码，gameKey 文件第一个字节应该是文件版本号，我这里新鲜下载的文件的第一个字节变成了 2，大抵是库需要更新了

您好，感谢您的细心检查。关于gameKey的版本2在9月6日左右就已被提交到了仓库中，新增字段为boolean camelliaKey;，因为平常没用到GameKey的version字段，所以才没有改，感谢您的细心观察。
